php:
  preset: laravel
  risky: true
  enabled:
    - long_array_syntax
    - alpha_ordered_imports
  disabled:
    - align_double_arrow
    - length_ordered_imports
    - unused_use
  finder:
    exclude:
      - modules
      - node_modules
      - storage
      - vendor
    name: "*.php"
    not-name: "*.blade.php"
